import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
* ${serviceType} FOR ${_m_comment}
*
* Created By @author ${_au}
* Date ${.now}
* Generated by Coder-Plus
*/
@Service
public class ${_m_cf}ServiceImpl implements ${_m_cf}Service {

    @Autowired
    private ${_m_cf}Repository ${_m}Repository;

    /**
    * 根据Example查询符合条件的结果列表
    *
    * @param ${_m}Example 查询条件
    * @return 结果列表
    */
    @Override
    public List<${_m_cf}> select${_m_cf}ListByExample(${_m_cf} ${_m}Example) {
        return ${_m}Mapper.select${_m_cf}ListByExample(${_m}Example);
    }

/**
* 根据DO参数查询符合条件的结果列表
*
* @param ${_m} 查询条件
* @return 结果列表
*/
@Override
public List<${_m_cf}> select${_m_cf}ListByParam(${_m_cf} ${_m}) {
return ${_m}Mapper.select${_m_cf}ListByParam(${_m});
}

/**
* 根据ID查询符合条件的结果
*
* @param id 主键
* @return 结果
*/
@Override
public ${_m_cf} select${_m_cf}ById(Long id) {
return ${_m}Mapper.select${_m_cf}ById(id);
}

/**
* 单条数据新增
*
* @param ${_m} 待入库数据
* @return 影响行数
*/
@Override
public Long insert${_m_cf}(${_m_cf} ${_m}) {
return ${_m}Mapper.insert${_m_cf}(${_m});
}

/**
* 根据ID对单条数据更新
*
* @param ${_m} 待入库数据
* @return 影响行数
*/
@Override
public Long update${_m_cf}ById(${_m_cf} ${_m}) {
return ${_m}Mapper.update${_m_cf}ById(${_m});
}

/**
* 根据主键删除
*
* @param id 主键
*/
@Override
public void delete${_m_cf}ById(Long id) {
${_m}Mapper.delete${_m_cf}ById(id);
}
"""
}