import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.sankuai.meituan.waimai.service.decoration.model.RecordQuery
import com.sankuai.meituan.waimai.service.decoration.model.RecordDO

import java.util.List;

/**
 * Repository实现 FOR 物料迁移表
 *
 * Created By @author XD.Wang
 * Date 2020-10-27 16:55:18
 * Generated by Coder-Plus
 */
@Service
public class RecordRepositoryImpl implements RecordRepository {

    @Autowired
    private RecordMapper recordMapper;

    /**
     * 根据DO参数查询符合条件的结果列表
     *
     * @param record 查询条件
     * @return 结果列表
     */
    @Override
    public List<RecordDO> selectRecordListByParam(RecordQuery record) {
        return recordMapper.selectRecordListByParam(record);
    }

    /**
     * 根据ID查询符合条件的结果
     *
     * @param id 主键
     * @return 结果
     */
    @Override
    public RecordDO selectRecordById(Long id) {
        return recordMapper.selectRecordById(id);
    }

    /**
     * 单条数据新增
     *
     * @param record 待入库数据
     * @return 影响行数
     */
    @Override
    public Long insertRecord(RecordQuery record) {
        return recordMapper.insertRecord(record);
    }

    /**
     * 根据ID对单条数据更新
     *
     * @param record 待入库数据
     * @return 影响行数
     */
    @Override
    public Long updateRecordById(RecordQuery record) {
        return recordMapper.updateRecordById(record);
    }

    /**
     * 根据主键删除
     *
     * @param id 主键
     */
    @Override
    public void deleteRecordById(Long id) {
        recordMapper.deleteRecordById(id);
    }

}