import java.util.ArrayList;
import java.util.List;

/**
 * Example FOR
 * <p>
 * Created By @author XD.Wang
 * Date 2020-9-11 16:44:55
 * Generated by Coder-Plus
 */
public class WmDecorationConfigExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> orCriteria;

    public WmDecorationConfigExample() {
        orCriteria = new ArrayList<>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOrCriteria() {
        return orCriteria;
    }

    public void or(Criteria criteria) {
        orCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        orCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (orCriteria.size() == 0) {
            orCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        return new Criteria();
    }

    public void clear() {
        orCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    protected abstract static class BaseCriteria {

        protected List<Criterion> criteria;

        protected BaseCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpRightsIsNull() {
            addCriterion("sp_rights is null");
        }

        public Criteria andSpRightsIsNotNull() {
            addCriterion("sp_rights is not null");
            return (Criteria) this;
        }

        public Criteria andSpRightsEqualTo(Integer value) {
            addCriterion("sp_rights =", value, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsNotEqualTo(Integer value) {
            addCriterion("sp_rights <>", value, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsGreaterThan(Integer value) {
            addCriterion("sp_rights >", value, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_rights >=", value, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsLessThan(Integer value) {
            addCriterion("sp_rights <", value, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsLessThanOrEqualTo(Integer value) {
            addCriterion("sp_rights <=", value, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsIn(List<Integer> values) {
            addCriterion("sp_rights in", values, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsNotIn(List<Integer> values) {
            addCriterion("sp_rights not in", values, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsBetween(Integer value1, Integer value2) {
            addCriterion("sp_rights between", value1, value2, "spRights");
            return (Criteria) this;
        }

        public Criteria andSpRightsNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_rights not between", value1, value2, "spRights");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdIsNull() {
            addCriterion("wm_poi_id is null");
        }

        public Criteria andWmPoiIdIsNotNull() {
            addCriterion("wm_poi_id is not null");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdEqualTo(Integer value) {
            addCriterion("wm_poi_id =", value, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdNotEqualTo(Integer value) {
            addCriterion("wm_poi_id <>", value, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdGreaterThan(Integer value) {
            addCriterion("wm_poi_id >", value, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wm_poi_id >=", value, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdLessThan(Integer value) {
            addCriterion("wm_poi_id <", value, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdLessThanOrEqualTo(Integer value) {
            addCriterion("wm_poi_id <=", value, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdIn(List<Integer> values) {
            addCriterion("wm_poi_id in", values, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdNotIn(List<Integer> values) {
            addCriterion("wm_poi_id not in", values, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdBetween(Integer value1, Integer value2) {
            addCriterion("wm_poi_id between", value1, value2, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andWmPoiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wm_poi_id not between", value1, value2, "wmPoiId");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Integer value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Integer value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Integer value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Integer value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Integer value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Integer> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Integer> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Integer value1, Integer value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andPresetRightsIsNull() {
            addCriterion("preset_rights is null");
        }

        public Criteria andPresetRightsIsNotNull() {
            addCriterion("preset_rights is not null");
            return (Criteria) this;
        }

        public Criteria andPresetRightsEqualTo(Integer value) {
            addCriterion("preset_rights =", value, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsNotEqualTo(Integer value) {
            addCriterion("preset_rights <>", value, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsGreaterThan(Integer value) {
            addCriterion("preset_rights >", value, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsGreaterThanOrEqualTo(Integer value) {
            addCriterion("preset_rights >=", value, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsLessThan(Integer value) {
            addCriterion("preset_rights <", value, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsLessThanOrEqualTo(Integer value) {
            addCriterion("preset_rights <=", value, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsIn(List<Integer> values) {
            addCriterion("preset_rights in", values, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsNotIn(List<Integer> values) {
            addCriterion("preset_rights not in", values, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsBetween(Integer value1, Integer value2) {
            addCriterion("preset_rights between", value1, value2, "presetRights");
            return (Criteria) this;
        }

        public Criteria andPresetRightsNotBetween(Integer value1, Integer value2) {
            addCriterion("preset_rights not between", value1, value2, "presetRights");
            return (Criteria) this;
        }

        public Criteria andMigratedIsNull() {
            addCriterion("migrated is null");
        }

        public Criteria andMigratedIsNotNull() {
            addCriterion("migrated is not null");
            return (Criteria) this;
        }

        public Criteria andMigratedEqualTo(Integer value) {
            addCriterion("migrated =", value, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedNotEqualTo(Integer value) {
            addCriterion("migrated <>", value, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedGreaterThan(Integer value) {
            addCriterion("migrated >", value, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedGreaterThanOrEqualTo(Integer value) {
            addCriterion("migrated >=", value, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedLessThan(Integer value) {
            addCriterion("migrated <", value, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedLessThanOrEqualTo(Integer value) {
            addCriterion("migrated <=", value, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedIn(List<Integer> values) {
            addCriterion("migrated in", values, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedNotIn(List<Integer> values) {
            addCriterion("migrated not in", values, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedBetween(Integer value1, Integer value2) {
            addCriterion("migrated between", value1, value2, "migrated");
            return (Criteria) this;
        }

        public Criteria andMigratedNotBetween(Integer value1, Integer value2) {
            addCriterion("migrated not between", value1, value2, "migrated");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Integer value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Integer value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Integer value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Integer value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Integer value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Integer> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Integer> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Integer value1, Integer value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andSpStatusIsNull() {
            addCriterion("sp_status is null");
        }

        public Criteria andSpStatusIsNotNull() {
            addCriterion("sp_status is not null");
            return (Criteria) this;
        }

        public Criteria andSpStatusEqualTo(Integer value) {
            addCriterion("sp_status =", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusNotEqualTo(Integer value) {
            addCriterion("sp_status <>", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusGreaterThan(Integer value) {
            addCriterion("sp_status >", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_status >=", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusLessThan(Integer value) {
            addCriterion("sp_status <", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sp_status <=", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusIn(List<Integer> values) {
            addCriterion("sp_status in", values, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusNotIn(List<Integer> values) {
            addCriterion("sp_status not in", values, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusBetween(Integer value1, Integer value2) {
            addCriterion("sp_status between", value1, value2, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_status not between", value1, value2, "spStatus");
            return (Criteria) this;
        }

        public Criteria andAcctIdIsNull() {
            addCriterion("acct_id is null");
        }

        public Criteria andAcctIdIsNotNull() {
            addCriterion("acct_id is not null");
            return (Criteria) this;
        }

        public Criteria andAcctIdEqualTo(Long value) {
            addCriterion("acct_id =", value, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdNotEqualTo(Long value) {
            addCriterion("acct_id <>", value, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdGreaterThan(Long value) {
            addCriterion("acct_id >", value, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdGreaterThanOrEqualTo(Long value) {
            addCriterion("acct_id >=", value, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdLessThan(Long value) {
            addCriterion("acct_id <", value, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdLessThanOrEqualTo(Long value) {
            addCriterion("acct_id <=", value, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdIn(List<Long> values) {
            addCriterion("acct_id in", values, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdNotIn(List<Long> values) {
            addCriterion("acct_id not in", values, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdBetween(Long value1, Long value2) {
            addCriterion("acct_id between", value1, value2, "acctId");
            return (Criteria) this;
        }

        public Criteria andAcctIdNotBetween(Long value1, Long value2) {
            addCriterion("acct_id not between", value1, value2, "acctId");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionIsNull() {
            addCriterion("theme_template_version is null");
        }

        public Criteria andThemeTemplateVersionIsNotNull() {
            addCriterion("theme_template_version is not null");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionEqualTo(Long value) {
            addCriterion("theme_template_version =", value, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionNotEqualTo(Long value) {
            addCriterion("theme_template_version <>", value, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionGreaterThan(Long value) {
            addCriterion("theme_template_version >", value, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("theme_template_version >=", value, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionLessThan(Long value) {
            addCriterion("theme_template_version <", value, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionLessThanOrEqualTo(Long value) {
            addCriterion("theme_template_version <=", value, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionIn(List<Long> values) {
            addCriterion("theme_template_version in", values, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionNotIn(List<Long> values) {
            addCriterion("theme_template_version not in", values, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionBetween(Long value1, Long value2) {
            addCriterion("theme_template_version between", value1, value2, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andThemeTemplateVersionNotBetween(Long value1, Long value2) {
            addCriterion("theme_template_version not between", value1, value2, "themeTemplateVersion");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusIsNull() {
            addCriterion("kangaroo_status is null");
        }

        public Criteria andKangarooStatusIsNotNull() {
            addCriterion("kangaroo_status is not null");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusEqualTo(Integer value) {
            addCriterion("kangaroo_status =", value, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusNotEqualTo(Integer value) {
            addCriterion("kangaroo_status <>", value, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusGreaterThan(Integer value) {
            addCriterion("kangaroo_status >", value, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("kangaroo_status >=", value, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusLessThan(Integer value) {
            addCriterion("kangaroo_status <", value, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusLessThanOrEqualTo(Integer value) {
            addCriterion("kangaroo_status <=", value, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusIn(List<Integer> values) {
            addCriterion("kangaroo_status in", values, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusNotIn(List<Integer> values) {
            addCriterion("kangaroo_status not in", values, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusBetween(Integer value1, Integer value2) {
            addCriterion("kangaroo_status between", value1, value2, "kangarooStatus");
            return (Criteria) this;
        }

        public Criteria andKangarooStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("kangaroo_status not between", value1, value2, "kangarooStatus");
            return (Criteria) this;
        }
    }

    public static class Criteria extends BaseCriteria {

        protected Criteria() {
            super();
        }

        public static class Criterion {

            private String condition;

            private Object value;

            private Object secondValue;

            private boolean noValue;

            private boolean singleValue;

            private boolean betweenValue;

            private boolean listValue;

            private String typeHandler;

            public String getCondition() {
                return condition;
            }

            public Object getValue() {
                return value;
            }

            public Object getSecondValue() {
                return secondValue;
            }

            public boolean isNoValue() {
                return noValue;
            }

            public boolean isSingleValue() {
                return singleValue;
            }

            public boolean isBetweenValue() {
                return betweenValue;
            }

            public boolean isListValue() {
                return listValue;
            }

            public String getTypeHandler() {
                return typeHandler;
            }

            protected Criterion(String condition) {
                super();
                this.condition = condition;
                this.typeHandler = null;
                this.noValue = true;
            }

            protected Criterion(String condition, Object value, String typeHandler) {
                super();
                this.condition = condition;
                this.value = value;
                this.typeHandler = typeHandler;
                if (value instanceof List<?>) {
                    this.listValue = true;
                } else {
                    this.singleValue = true;
                }
            }

            protected Criterion(String condition, Object value) {
                this(condition, value, null);
            }

            protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
                super();
                this.condition = condition;
                this.value = value;
                this.secondValue = secondValue;
                this.typeHandler = typeHandler;
                this.betweenValue = true;
            }

            protected Criterion(String condition, Object value, Object secondValue) {
                this(condition, value, secondValue, null);
            }
        }
    }