import java.util.Date;

/**
 * POJO FOR 
 *
 * Created By @author XD.Wang
 * Date 2020-9-14 16:17:40
 * Generated by Coder-Plus
 */
public class WmEPoiSignagePic {

    /**
     * 
     */
    private Long id;

    /**
     * 
     */
    private Integer createTime;

    /**
     * 
     */
    private Integer updateTime;

    /**
     * 门店所属分组
     */
    private String groupId;

    /**
     * 门店id
     */
    private Long wmPoiId;

    /**
     * 店铺招牌图url
     */
    private String signagePicUrl;

    /**
     * 访问器【】
     */
    public Long getId() {
        return id;
    }

    /**
     * 修改器【】
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 访问器【】
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * 修改器【】
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * 访问器【】
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * 修改器【】
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 访问器【门店所属分组】
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * 修改器【门店所属分组】
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * 访问器【门店id】
     */
    public Long getWmPoiId() {
        return wmPoiId;
    }

    /**
     * 修改器【门店id】
     */
    public void setWmPoiId(Long wmPoiId) {
        this.wmPoiId = wmPoiId;
    }

    /**
     * 访问器【店铺招牌图url】
     */
    public String getSignagePicUrl() {
        return signagePicUrl;
    }

    /**
     * 修改器【店铺招牌图url】
     */
    public void setSignagePicUrl(String signagePicUrl) {
        this.signagePicUrl = signagePicUrl;
    }
}