import java.util.Date;
import java.math.BigDecimal;

/**
 * POJO FOR 物料迁移表
 *
 * Created By @author XD.Wang
 * Date 2020-10-27 16:55:18
 * Generated by Coder-Plus
 */
public class RecordDO {

    /**
     * 物料类型(1:海报；2:招牌；3:关键词)
     */
    private Integer bizTabType;

    /**
     * 物料id
     */
    private Long materialId;

    /**
     * id
     */
    private Long id;

    /**
     * 原业务id
     */
    private Long bizId;

    /**
     * 访问器【物料类型(1:海报；2:招牌；3:关键词)】
     */
    public Integer getBizTabType() {
        return bizTabType;
    }

    /**
     * 修改器【物料类型(1:海报；2:招牌；3:关键词)】
     */
    public void setBizTabType(Integer bizTabType) {
        this.bizTabType = bizTabType;
    }

    /**
     * 访问器【物料id】
     */
    public Long getMaterialId() {
        return materialId;
    }

    /**
     * 修改器【物料id】
     */
    public void setMaterialId(Long materialId) {
        this.materialId = materialId;
    }

    /**
     * 访问器【id】
     */
    public Long getId() {
        return id;
    }

    /**
     * 修改器【id】
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 访问器【原业务id】
     */
    public Long getBizId() {
        return bizId;
    }

    /**
     * 修改器【原业务id】
     */
    public void setBizId(Long bizId) {
        this.bizId = bizId;
    }
}